/*
 * TSEN_prog.c
 *
 *  Created on: Mar 27, 2016
 *      Author: m.mamdooh
 */
#include "type.h"
#include "DIO-interface.h"
#include "ADC_interface.h"
#include "TSEN_interface.h"
#include "TSEN_config.h"

#if(TSEN_u8SEN_NUMS==1)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN};
#elif(TSEN_u8SEN_NUMS==2)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN};
#elif(TSEN_u8SEN_NUMS==3)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN};
#elif(TSEN_u8SEN_NUMS==4)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN,TSEN_u8SEN4_PIN};
#elif(TSEN_u8SEN_NUMS==5)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN,TSEN_u8SEN4_PIN,TSEN_u8SEN5_PIN};
#elif(TSEN_u8SEN_NUMS==6)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN,TSEN_u8SEN4_PIN,TSEN_u8SEN5_PIN,TSEN_u8SEN6_PIN};
#elif(TSEN_u8SEN_NUMS==7)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN,TSEN_u8SEN4_PIN,TSEN_u8SEN5_PIN,TSEN_u8SEN6_PIN,TSEN_u8SEN7_PIN};
#elif(TSEN_u8SEN_NUMS==8)
u8 TSEN_u8SNSORS[TSEN_u8SEN_NUMS]={TSEN_u8SEN1_PIN,TSEN_u8SEN2_PIN,TSEN_u8SEN3_PIN,TSEN_u8SEN4_PIN,TSEN_u8SEN5_PIN,TSEN_u8SEN6_PIN,TSEN_u8SEN7_PIN,TSEN_u8SEN8_PIN};
#endif

u8 const CHCKERR[]={ok,error};

u8 TSEN_u8ReadTSensr(u8 Copy_SenIdx , u16 *Copy_PtrToVal)
{
	u16 Local_u8AdcVal ;
	ADC_u8ReadCh_SSht(TSEN_u8SNSORS[Copy_SenIdx ],&Local_u8AdcVal);
	Local_u8AdcVal/=2 ;
	*Copy_PtrToVal=Local_u8AdcVal;

	return CHCKERR[Copy_SenIdx>8];
}
